export enum DressageModels {
  OLYMPIC = "Olympic",
  TRAINING = "Training",
}

export enum CubiModels {
  MAXI = "Maxi",
  MINI = "Mini",
}

export enum CucchiaiModels {
  DE,
  PS,
}

export enum SegnaleticaModels {
  LIGHT = "Light",
  PROFESSIONAL = "Professional",
}

export enum Material {
  ACCIAIO_ZINCATO,
  PLASTICA,
  POLIETILENE,
  POLIPROPILENE,
  PVC,
  TECNOPOLIMERO,
}

export const DressageData = {
  SIZE_20x40: { letters: 8, modules: 60, size: "20x40" },
  SIZE_20x60: { letters: 12, modules: 80, size: "20x60" },
};

export enum ProductId {
  DRESSAGE_OLYMPIC_LETTERA = "DRESSAGE_OLYMPIC_LETTERA",
  DRESSAGE_OLYMPIC_MODULO = "DRESSAGE_OLYMPIC_MODULO",
  DRESSAGE_OLYMPIC_RETTANGOLO_20X40 = "DRESSAGE_OLYMPIC_RETTANGOLO_20X40",
  DRESSAGE_OLYMPIC_RETTANGOLO_20X60 = "DRESSAGE_OLYMPIC_RETTANGOLO_20X60",
  DRESSAGE_TRAINING_LETTERE_8_KIT = "DRESSAGE_TRAINING_LETTERE_8_KIT",
  DRESSAGE_TRAINING_LETTERE_12_KIT = "DRESSAGE_TRAINING_LETTERE_12_KIT",
  DRESSAGE_TRAINING_MODULO = "DRESSAGE_TRAINING_MODULO",
  DRESSAGE_TRAINING_RETTANGOLO_20X40 = "DRESSAGE_TRAINING_RETTANGOLO_20X40",
  DRESSAGE_TRAINING_RETTANGOLO_20X60 = "DRESSAGE_TRAINING_RETTANGOLO_20X60",
  OSTACOLI_BANDIERINE = "OSTACOLI_BANDIERINE",
  BARRIERA_3_MT = "BARRIERA_3_MT",
  CANDELIERE_CON_PIEDE_IN_PVC_170 = "CANDELIERE_CON_PIEDE_IN_PVC_170",
  CANDELIERE_CON_PIEDE_IN_PVC_190 = "CANDELIERE_CON_PIEDE_IN_PVC_190",
  CANDELIERE_CON_PIEDE_IN_PVC = "CANDELIERE_CON_PIEDE_IN_PVC",
  CAVALLETTI_CAPRILLI_BARRIERA_KIT = "CAVALLETTI_CAPRILLI_BARRIERA_KIT",
  CAVALLETTI_CAPRILLI = "CAVALLETTI_CAPRILLI",
  CUBI_MAXI = "CUBI_MAXI",
  CUBI_MINI = "CUBI_MINI",
  CUCCHIAIO_DE = "CUCCHIAIO_DE",
  CUCCHIAIO_PS = "CUCCHIAIO_PS",
  FOSSO = "FOSSO",
  LAMA_DE_150 = "LAMA_DE_150",
  LAMA_DE_50_150_CM = "LAMA_DE_50_150_CM",
  LAMA_DE_50 = "LAMA_DE_50",
  NUMERO_CAMPO_OSTACOLI_PROFESSIONAL = "NUMERO_CAMPO_OSTACOLI_PROFESSIONAL",
  SUPPORTO_SICUREZZA = "SUPPORTO_SICUREZZA",
  RECINZIONE_1_FILAGNA = "RECINZIONE_1_FILAGNA",
  RECINZIONE_2_FILAGNE = "RECINZIONE_2_FILAGNE",
  RECINZIONE_3_FILAGNE = "RECINZIONE_3_FILAGNE",
  RECINZIONE_4_FILAGNE = "RECINZIONE_4_FILAGNE",
  RECINZIONE_PIEDE_MOBILE = "RECINZIONE_PIEDE_MOBILE",
  TONDINO_1320 = "TONDINO_1320",
  TONDINO_1500 = "TONDINO_1500",
  TONDINO_1660 = "TONDINO_1660",
  TONDINO_1830 = "TONDINO_1830",
  TONDINO_1990 = "TONDINO_1990",
  GIOSTRA_4_CAVALLI_1200_SOLO_MOTORE = "GIOSTRA_4_CAVALLI_1200_SOLO_MOTORE",
  GIOSTRA_6_CAVALLI_1440_SOLO_MOTORE = "GIOSTRA_6_CAVALLI_1440_SOLO_MOTORE",
  GIOSTRA_6_CAVALLI_1600_SOLO_MOTORE = "GIOSTRA_6_CAVALLI_1600_SOLO_MOTORE",
  GIOSTRA_6_CAVALLI_1760_SOLO_MOTORE = "GIOSTRA_6_CAVALLI_1760_SOLO_MOTORE",
  GIOSTRA_8_CAVALLI_1920_SOLO_MOTORE = "GIOSTRA_8_CAVALLI_1920_SOLO_MOTORE",
}
