import { PrismaClient, Product, ProductId } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const PRODUCTS: Product[] = [
    {
      depth: null,
      diameter: null,
      height: 70,
      id: ProductId.DRESSAGE_OLYMPIC_LETTERA,
      length: null,
      price: 62,
      weight: 0.25,
      width: 39,
    },
    {
      depth: null,
      diameter: null,
      height: 37,
      id: ProductId.DRESSAGE_OLYMPIC_MODULO,
      length: null,
      price: null,
      weight: 0.5,
      width: 200,
    },
    {
      depth: null,
      diameter: null,
      height: null,
      id: ProductId.DRESSAGE_OLYMPIC_RETTANGOLO_20X40,
      length: null,
      price: 5940,
      weight: null,
      width: null,
    },
    {
      depth: null,
      diameter: null,
      height: null,
      id: ProductId.DRESSAGE_OLYMPIC_RETTANGOLO_20X60,
      length: null,
      price: 7920,
      weight: null,
      width: null,
    },
    {
      depth: null,
      diameter: null,
      height: 30,
      id: ProductId.DRESSAGE_TRAINING_LETTERA,
      length: null,
      price: 25.5,
      weight: 0.5,
      width: 20,
    },
    {
      depth: null,
      diameter: null,
      height: 28.5,
      id: ProductId.DRESSAGE_TRAINING_MODULO,
      length: null,
      price: null,
      weight: 0.3,
      width: 200,
    },
    {
      depth: null,
      diameter: null,
      height: null,
      id: ProductId.DRESSAGE_TRAINING_RETTANGOLO_20X40,
      length: null,
      price: 1400,
      weight: null,
      width: null,
    },
    {
      depth: null,
      diameter: null,
      height: null,
      id: ProductId.DRESSAGE_TRAINING_RETTANGOLO_20X60,
      length: null,
      price: 1800,
      weight: null,
      width: null,
    },
    {
      id: ProductId.RECINZIONE_1_FILAGNA,
      depth: null,
      diameter: null,
      height: 125,
      length: null,
      price: null,
      weight: null,
      width: null,
    },
    {
      id: ProductId.RECINZIONE_2_FILAGNE,
      depth: null,
      diameter: null,
      height: 140,
      length: null,
      price: null,
      weight: null,
      width: null,
    },
    {
      id: ProductId.RECINZIONE_3_FILAGNE,
      depth: null,
      diameter: null,
      height: 165,
      length: null,
      price: null,
      weight: null,
      width: null,
    },
    {
      id: ProductId.RECINZIONE_4_FILAGNE,
      depth: null,
      diameter: null,
      height: 195,
      length: null,
      price: null,
      weight: null,
      width: null,
    },
    {
      id: ProductId.RECINZIONE_PIEDE_MOBILE,
      depth: null,
      diameter: null,
      height: 30,
      price: 35,
      length: null,
      weight: null,
      width: null,
    },
    {
      depth: null,
      diameter: 9.5,
      height: null,
      id: ProductId.OSTACOLI_BARRIERA_3_MT,
      length: 299,
      price: 50,
      weight: 9.75,
      width: null,
    },
    {
      depth: null,
      diameter: null,
      height: 8,
      id: ProductId.OSTACOLI_FOSSO,
      length: 150,
      price: 440,
      weight: null,
      width: 280,
    },
    {
      id: ProductId.OSTACOLI_CAVALLETTI_CAPRILLI,
      depth: null,
      diameter: null,
      height: 50,
      length: null,
      price: 34,
      weight: null,
      width: 50,
    },
    {
      id: ProductId.OSTACOLI_CAVALLETTI_CAPRILLI_BARRIERA_KIT,
      depth: null,
      diameter: null,
      height: 50,
      length: 200,
      price: null,
      weight: 5.3,
      width: 50,
    },
    {
      depth: null,
      diameter: null,
      height: 57,
      id: ProductId.OSTACOLI_CUBI_MINI,
      length: 37,
      price: 38.5,
      weight: 3,
      width: 35,
    },
    {
      depth: null,
      diameter: null,
      height: 70,
      id: ProductId.OSTACOLI_CUBI_MAXI,
      length: 57,
      price: 63.5,
      weight: 5,
      width: 37,
    },
    {
      id: ProductId.OSTACOLI_CANDELIERE_CON_PIEDE_IN_PVC_170,
      depth: null,
      diameter: null,
      height: 170,
      length: 72,
      price: 89,
      weight: 7,
      width: 72,
    },
    {
      id: ProductId.OSTACOLI_CANDELIERE_CON_PIEDE_IN_PVC_190,
      depth: null,
      diameter: null,
      height: 190,
      length: 72,
      price: 96,
      weight: 7,
      width: 72,
    },
    {
      id: ProductId.OSTACOLI_LAMA_DE_50,
      depth: null,
      diameter: null,
      height: null,
      weight: null,
      length: 500,
      width: 65,
      price: 8.5,
    },
    {
      id: ProductId.OSTACOLI_LAMA_DE_150,
      depth: null,
      diameter: null,
      height: null,
      weight: null,
      length: 1500,
      width: 65,
      price: 17,
    },
    {
      depth: 20,
      diameter: null,
      height: null,
      id: ProductId.OSTACOLI_CUCCHIAIO_DE,
      length: null,
      price: 3.5,
      weight: 0.15,
      width: null,
    },
    {
      id: ProductId.OSTACOLI_CUCCHIAIO_PS,
      depth: null,
      diameter: null,
      height: null,
      length: null,
      price: 4.5,
      weight: null,
      width: null,
    },
    {
      id: ProductId.OSTACOLI_SUPPORTO_SICUREZZA,
      depth: null,
      diameter: null,
      height: null,
      length: null,
      width: 37,
      weight: 0.05,
      price: 4,
    },
    {
      id: ProductId.OSTACOLI_BANDIERINE,
      depth: null,
      diameter: null,
      height: null,
      length: null,
      weight: null,
      width: null,
      price: 2.1,
    },
    {
      id: ProductId.OSTACOLI_NUMERO_CAMPO_OSTACOLI_PROFESSIONAL,
      depth: null,
      diameter: null,
      length: null,
      width: 200,
      height: 300,
      weight: 2.3,
      price: 26,
    },
    {
      id: ProductId.OSTACOLI_NUMERO_CAMPO_OSTACOLI_LIGHT,
      depth: null,
      diameter: null,
      length: null,
      width: 330,
      height: 330,
      weight: 1.25,
      price: 16,
    },
  ];

  PRODUCTS.map(async (product) => {
    await prisma.product.upsert({
      where: { id: product.id },
      update: product,
      create: product,
    });
  });
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
